#!/bin/bash
# 18.10.2012/S.Lehti
# 23.10.2012/LAW added support for use from outside lxplus

#REPOSITORY="http://cmsdoc.cern.ch/~${USER}/HiggsAnalysis.git"
REPOSITORY="http://cmsdoc.cern.ch/~slehti/HiggsAnalysis.git"
DIRPREFIX=""
MYUSER=$USER

if [ $1 ]; then
    BRANCH=$1
else
    BRANCH="master"
#    echo
#    echo "        Branch not set. Please define branch"
#    if [[ $0 =~ ".*/(\S+)" ]]; then
#	echo "        Usage: "${BASH_REMATCH[1]}" <branch>"
#    fi
#    echo
#    echo "        Available branches:"
#    output=$(git-ls-remote ${REPOSITORY})
#    for line in $output
#    do
#	if [[ $line =~ "refs/heads/(\S+)" ]]; then
#	    echo "                "${BASH_REMATCH[1]}
#	fi
#	
#    done
#    exit
fi

git clone ${REPOSITORY}
#git clone $HOME/public/html/HiggsAnalysis.git

cd HiggsAnalysis
if [[ $HOST == lxplus* ]]; then
    git remote add public $HOME/public/html/HiggsAnalysis.git
else
    DIRPREFIX="http://cmsdoc.cern.ch/"
    git remote add public ssh://${USER}@lxplus.cern.ch/afs/cern.ch/user/${MYUSER:0:1}/$USER/public/html/HiggsAnalysis.git
fi
git remote add sami ${DIRPREFIX}~slehti/public/html/HiggsAnalysis.git
git remote add matti ${DIRPREFIX}~mkortela/public/html/HiggsAnalysis.git
git remote add lauri ${DIRPREFIX}~wendland/public/html/HiggsAnalysis.git
git remote add ritva ${DIRPREFIX}~kinnunen/public/html/HiggsAnalysis.git
git remote add alexandros ${DIRPREFIX}~attikis/public/html/HiggsAnalysis.git
git remote add attikis https://github.com/attikis/HiggsAnalysis.git
#git remote add tapio ${DIRPREFIX}~tlampen/public/html/HiggsAnalysis.git
#git remote add cristina ${DIRPREFIX}~cferro/public/html/HiggsAnalysis.git
git remote add stefan ${DIRPREFIX}~strichte/public/html/HiggsAnalysis.git
git remote add erik ${DIRPREFIX}~epekkari/public/html/HiggsAnalysis.git
git remote add santeri ${DIRPREFIX}~slaurila/public/html/HiggsAnalysis.git
git remote add joona ${DIRPREFIX}~jhavukai/public/html/HiggsAnalysis.git
git remote add heitor https://github.com/heitorPB/HiggsAnalysis.git
git remote add laura https://github.com/sorda/HiggsAnalysis.git

if [ ${BRANCH} != "master" ]; then
    git branch --track ${BRANCH} origin/${BRANCH}
fi
if [ ${BRANCH} == "2011" ]; then
    git branch --track 2012 origin/2012
fi
git checkout ${BRANCH}
git branch -a

cd ..

#if [ ! $2 ]; then
#    ./HiggsAnalysis/HeavyChHiggsToTauNu/test/checkoutTags.sh
#fi

# Show list of git aliases 
#cd HiggsAnalysis
#echo "The following git aliases have been set up (check that the path for public is correct!):"
#git remote -v
#cd ..

